// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package demobase

type Account struct {
	ID       int64  `db:"id" json:"id"`
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
	Enabled  bool   `db:"enabled" json:"enabled"`
}
