// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package userdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID      int64
	Channel string
	Title   string
	Default bool
}

type User struct {
	ID         pgtype.UUID
	Username   string
	GivenName  string
	FamilyName string
	Enabled    bool
}

type UserChat struct {
	UserID     pgtype.UUID
	ChatID     int64
	CanPublish bool
}
